### ISSUE TITLE
Quick Output question

### ISSUE THREAD

**Issue by plaidam** [kadirnar/ComfyUI-YOLO#3]
Any idea how to output the boxes and labels separately from the input image, like on a transparent PNG or something?

**Comment by kadirnar** [comment]
Is there a sample image? Have you ever tested it?

**Comment by plaidam** [comment]
<img width="1674" alt="example" src="https://github.com/kadirnar/ComfyUI-YOLO/assets/6028016/df3cdaaf-5901-4eca-8abe-2a983a2f182c">

I did a quick Photoshop with one of your examples to show what I mean. Would love to be able to output the boxes and labels separately as an image. Let me know if this makes sense or if it's possible?

**Comment by ghostrunner-art** [comment]
I also need such a function, it is very practical.

**Comment by plaidam** [comment]
Please let me know when you have updated with this feature. Thanks again

**Comment by kadirnar** [comment]
@plaidam @ghostrunner-art 

I added the Bbox2Vis node feature. You can test it. I can add any other features you want.
https://github.com/kadirnar/ComfyUI-YOLO?tab=readme-ov-file#ultralytics-bbox-visualization

**Comment by plaidam** [comment]
Ok, I updated and matched your Ultralytics Bbox Visualization workflow and am still unable to make an output like the one I showed above. I tried leaving the image input empty but got an error. I even tried using a blank colour node as a image input but still got the original input image. If theirs any way to update to allow this, that would be great. thanks.

**Comment by kadirnar** [comment]
Can you share an example image so I don't get the same error?

**Comment by plaidam** [comment]
ok, thanks. I was able to get a empty output by using a custom colour node. 
Any idea how I might get the labels as well?

<img width="1818" alt="Screenshot 2024-06-26 at 10 23 26 AM" src="https://github.com/kadirnar/ComfyUI-YOLO/assets/6028016/f04387f4-1fd9-4749-a3ea-805c50f66788">

**Comment by kadirnar** [comment]
Do you want label names too?

**Comment by plaidam** [comment]
If possible, that would be great!

**Comment by kadirnar** [comment]
I will add it this evening. Is there any other feature you want?

**Comment by plaidam** [comment]
Wishlist:
- Font size and line width like the "Ultralytics Visualization" node.
- Right now I have to make multiple "BBox Visualization" modes for various index's, if I could get all the visible index's output from one node instead would be great.
- Option to Toggle label on off.
- Transparent PNG output - right now I have to use a blank color that I will green screen out later. Great if it just output the boxes and labels with a alpha.

**Comment by kadirnar** [comment]
@plaidam 
<img width="1114" alt="image" src="https://github.com/kadirnar/ComfyUI-YOLO/assets/36204372/30931ff2-a0d2-400e-80c2-031bc0197a8c">


I added the Label feature. I will add other features today. I will add more parameters related to visualization.

**Comment by kadirnar** [comment]
I added 3 features. I don't know about transparent images.

<img width="1572" alt="image" src="https://github.com/kadirnar/ComfyUI-YOLO/assets/36204372/f31199bd-1db6-4fc9-940d-64e50029602e">

**Comment by plaidam** [comment]
Amazing. thanks!

**Comment by plaidam** [comment]
Works great!

<img width="1378" alt="Screenshot 2024-07-09 at 12 28 10 PM" src="https://github.com/kadirnar/ComfyUI-YOLO/assets/6028016/5aaf0f25-65a1-47bb-940e-995649aa2533">
