### ISSUE TITLE
Feature request, cleaner output.

### ISSUE THREAD

**Issue by ghostrunner-art** [kadirnar/ComfyUI-YOLO#4]
Hello, thank you for your contribution to the open source community.

I'm using this plugin. But the content output by the node should be clearer. It is convenient for us to use the results detected by Yolo-world for processing.

Feature requests are as follows:
1. It is necessary to use keywords to detect input images. For example: through the keyword "car", only cars are detected in the picture.
2. More diversified output is needed. For example, you can directly output pictures in "BOX".
The "Mask" list can be output and the mask can be retrieved more clearly.
3. Make more expansions based on the characteristics of the new version of "YOLO".

Looking forward to your next release.

**Comment by ghostrunner-art** [comment]
It is best to optimize the recognition of "face, hands, feet" and other content, because these are the parts that are difficult to solve for the SD model.
Users can extract them individually for secondary processing.
I believe this is more interesting.

**Comment by kadirnar** [comment]
Example:
<img width="1696" alt="image" src="https://github.com/kadirnar/ComfyUI-YOLO/assets/36204372/85b26690-b55e-499c-8872-c05455cdcbc7">

**Comment by kadirnar** [comment]
Face,Hand and Person:

https://huggingface.co/Bingsu/adetailer/tree/main
<img width="525" alt="image" src="https://github.com/kadirnar/ComfyUI-YOLO/assets/36204372/8d659d88-eab0-44ea-9350-f2bc1a08f673">

**Comment by kadirnar** [comment]
You can download and use the Yolo-world model. You should upload it to models/ultralicsts folder. 

CustomUltralyticsModelLoader:
https://github.com/kadirnar/ComfyUI-YOLO/blob/main/nodes.py#L342

**Comment by ghostrunner-art** [comment]
Please ask how to better output "mask".
There are also how to use "PROBABILITIES", "KEYPOINTS" and "OBB".

**Comment by kadirnar** [comment]
What is better output? Want to increase accuracy?

**Comment by ethanfel** [comment]
> What is better output? Want to increase accuracy?

I think he's asking how to use the output. Like the mask output how to use it as a comfyui mask ?
